create table users (
  id bigint generated by default as identity primary key,
  google_id text not null,
  name text not null,
  email text not null unique,
  picture text,
  is_subscribed boolean default false,
  is_admin boolean default false
);


-- trigger



